image: node:14.8-alpine

stages:
  - lint
  - build

before_script:
  - npm install --silent
cache:
  paths:
    - node_modules/

lint:
  stage: lint
  script: npm run lint

build-code:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
